name: Build rpv-ghidra

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - rpv-ghidra/src/**
      - rpv-ghidra/build.gradle
      - rpv-ghidra/extension.properties

jobs:
  build-rpv-ghidra:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Restore Ghidra
        id: cache-ghidra
        uses: actions/cache@v4
        with:
          path: ghidra
          key: static-key-for-now

      - name: Download Ghidra
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          wget 'https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.3.1_build/ghidra_11.3.1_PUBLIC_20250219.zip'
          CHECKSUM=$(sha256sum ghidra_11.3.1_PUBLIC_20250219.zip | cut -f1 -d' ')
          if [ "$CHECKSUM" = "bcda0a9de8993444766cc255964c65c042b291ddaf6c50d654e316e442b441fa" ]; then
              unzip ghidra_11.3.1_PUBLIC_20250219.zip
              mv ghidra_11.3.1_PUBLIC ghidra
          fi

      - name: Build rpv-ghidra
        if: ${{ hashFiles('ghidra/LICENSE') != '' }}
        run: |
          docker compose up
          sudo mv rpv-ghidra/dist/ghidra_*_rpv-ghidra.zip rpv-ghidra.zip

      - name: Archive rpv-ghidra
        uses: actions/upload-artifact@v4
        with:
          name: rpv-ghidra-build
          path: rpv-ghidra.zip
